import  "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";

export const metadata = {
  title: "TITULO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AddBootstrap/>
        {children}</body>
    </html>
  );
}